version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'       
  customerservice:
    ports: 
      - '9000:80'
      - '9001:443'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo  
